name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
# no need to bother caching bun deps
# https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            "check:format" = { run = "dprint check --excludes mise.toml" }
            "check" = { depends = "check:*" }
            [tools]
            dprint = "latest"
      - run: mise r check
